repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-json
        exclude: resume/.vscode/extensions.json
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "50c5478" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml)$
